[package]
name = "backends"
version.workspace = true
edition.workspace = true

[dependencies]
egg = { workspace = true }
macros = { workspace = true }
core = { workspace = true }
storage = { workspace = true }