[package]
name = "examples"
version.workspace = true
edition.workspace = true

[dependencies]
macros = { workspace = true }
core = { workspace = true }
storage = { workspace = true }
backends = { workspace = true }