[package]
name = "examples"
version.workspace = true
edition.workspace = true

[dependencies]
num-traits = { workspace = true }
macros = { workspace = true }
core = { workspace = true }
storage = { workspace = true }
backends = { workspace = true }